# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Turnstr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Turnstr
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.3’
pod 'AlamofireImage', '~> 3.0’
pod 'RMMapper'
pod 'NVActivityIndicatorView'
end
