# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Turnstr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Turnstr
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.3’
pod 'AlamofireImage', '~> 3.0’
pod 'RMMapper'
pod 'NVActivityIndicatorView'
pod 'ObjectMapper'
pod 'Kingfisher', '~> 3.0'
pod 'KSPhotoBrowser'
pod 'SVProgressHUD'

# Facebook SDK
pod 'FacebookCore', '~> 0.2'
pod 'FacebookLogin', '~> 0.2'
pod 'FacebookShare', '~> 0.2'
pod 'FBSDKCoreKit', '~> 4.22.1'
pod 'FBSDKLoginKit', '~> 4.22.1'
pod 'FBSDKShareKit', '~> 4.22.1'

#Firebase
pod 'Firebase/Core'
pod 'Firebase/Messaging'

#Twitter
pod 'TwitterKit'

#SendBird
pod 'SendBirdSDK'
pod 'GrowingTextView'

end
